create table if not exists public.athlete_highlights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  title text not null,
  url text not null,
  created_at timestamptz not null default now()
);

alter table public.athlete_highlights enable row level security;

grant select, insert, update, delete on public.athlete_highlights to authenticated;
grant usage, select on sequence public.athlete_highlights_id_seq to authenticated;

drop policy if exists "Users can read their athlete highlights" on public.athlete_highlights;
create policy "Users can read their athlete highlights"
on public.athlete_highlights for select
using (auth.uid() = user_id);

drop policy if exists "Users can create their athlete highlights" on public.athlete_highlights;
create policy "Users can create their athlete highlights"
on public.athlete_highlights for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their athlete highlights" on public.athlete_highlights;
create policy "Users can update their athlete highlights"
on public.athlete_highlights for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their athlete highlights" on public.athlete_highlights;
create policy "Users can delete their athlete highlights"
on public.athlete_highlights for delete
using (auth.uid() = user_id);

drop policy if exists "Users can delete their own profile picture" on storage.objects;
create policy "Users can delete their own profile picture"
on storage.objects for delete
using (
  bucket_id = 'profile-pictures'
  and auth.uid()::text = (storage.foldername(name))[1]
);

notify pgrst, 'reload schema';
