-- AthleteAura Community Feed Upgrades
-- Run this after community-feed-schema.sql.

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create or replace view public.community_profiles as
select
  p.user_id,
  p.role,
  p.full_name,
  p.first_name,
  p.last_name,
  p.country,
  p.current_club,
  p.sport,
  ap.profile_pic_url
from public.profiles p
left join public.athlete_profiles ap on ap.user_id = p.user_id;

alter table public.post_reports enable row level security;

grant usage on schema public to authenticated;
grant select on public.community_profiles to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, delete on public.comments to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant insert on public.post_reports to authenticated;
grant usage, select on sequence public.post_reports_id_seq to authenticated;

drop policy if exists "Users can update their own posts" on public.posts;
create policy "Users can update their own posts"
on public.posts for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can report posts" on public.post_reports;
create policy "Users can report posts"
on public.post_reports for insert
to authenticated
with check (auth.uid() = user_id);

notify pgrst, 'reload schema';
