-- AthleteAura Community Feed
-- Run this in Supabase SQL Editor after your profile schema exists.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0 and char_length(content) <= 2000),
  category text not null check (
    category in (
      'Training',
      'Fitness',
      'Nutrition',
      'Achievement',
      'Question',
      'General Sports'
    )
  ),
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  parent_comment_id bigint references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0 and char_length(content) <= 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create table if not exists public.post_saves (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.user_follows (
  follower_id uuid not null references public.profiles(user_id) on delete cascade,
  following_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create or replace view public.community_profiles as
select
  p.user_id,
  p.role,
  p.full_name,
  p.first_name,
  p.last_name,
  p.country,
  p.current_club,
  p.sport,
  ap.profile_pic_url
from public.profiles p
left join public.athlete_profiles ap on ap.user_id = p.user_id;

alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.comment_likes enable row level security;
alter table public.post_saves enable row level security;
alter table public.user_follows enable row level security;
alter table public.post_reports enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, delete on public.comments to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant select, insert, delete on public.comment_likes to authenticated;
grant select, insert, delete on public.post_saves to authenticated;
grant select, insert, delete on public.user_follows to authenticated;
grant insert on public.post_reports to authenticated;
grant select on public.community_profiles to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;
grant usage, select on sequence public.post_reports_id_seq to authenticated;

drop policy if exists "Authenticated users can read posts" on public.posts;
create policy "Authenticated users can read posts"
on public.posts for select
to authenticated
using (true);

drop policy if exists "Users can create their own posts" on public.posts;
create policy "Users can create their own posts"
on public.posts for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own posts" on public.posts;
create policy "Users can delete their own posts"
on public.posts for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can update their own posts" on public.posts;
create policy "Users can update their own posts"
on public.posts for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can read comments" on public.comments;
create policy "Authenticated users can read comments"
on public.comments for select
to authenticated
using (true);

drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
on public.comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own comments" on public.comments;
create policy "Users can delete their own comments"
on public.comments for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can read likes" on public.post_likes;
create policy "Authenticated users can read likes"
on public.post_likes for select
to authenticated
using (true);

drop policy if exists "Users can like as themselves" on public.post_likes;
create policy "Users can like as themselves"
on public.post_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unlike as themselves" on public.post_likes;
create policy "Users can unlike as themselves"
on public.post_likes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can read comment likes" on public.comment_likes;
create policy "Authenticated users can read comment likes"
on public.comment_likes for select
to authenticated
using (true);

drop policy if exists "Users can like comments as themselves" on public.comment_likes;
create policy "Users can like comments as themselves"
on public.comment_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unlike comments as themselves" on public.comment_likes;
create policy "Users can unlike comments as themselves"
on public.comment_likes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read their saved posts" on public.post_saves;
create policy "Users can read their saved posts"
on public.post_saves for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can save posts as themselves" on public.post_saves;
create policy "Users can save posts as themselves"
on public.post_saves for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unsave their saved posts" on public.post_saves;
create policy "Users can unsave their saved posts"
on public.post_saves for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can read follows" on public.user_follows;
create policy "Authenticated users can read follows"
on public.user_follows for select
to authenticated
using (true);

drop policy if exists "Users can follow as themselves" on public.user_follows;
create policy "Users can follow as themselves"
on public.user_follows for insert
to authenticated
with check (auth.uid() = follower_id and follower_id <> following_id);

drop policy if exists "Users can unfollow as themselves" on public.user_follows;
create policy "Users can unfollow as themselves"
on public.user_follows for delete
to authenticated
using (auth.uid() = follower_id);

drop policy if exists "Users can report posts" on public.post_reports;
create policy "Users can report posts"
on public.post_reports for insert
to authenticated
with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Users can upload their own post images" on storage.objects;
create policy "Users can upload their own post images"
on storage.objects for insert
with check (
  bucket_id = 'post-images'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "Users can update their own post images" on storage.objects;
create policy "Users can update their own post images"
on storage.objects for update
using (
  bucket_id = 'post-images'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'post-images'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "Users can delete their own post images" on storage.objects;
create policy "Users can delete their own post images"
on storage.objects for delete
using (
  bucket_id = 'post-images'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "Post images are public" on storage.objects;
create policy "Post images are public"
on storage.objects for select
using (bucket_id = 'post-images');

notify pgrst, 'reload schema';
